export function getAgentGuideMarkdown(): string {
  return [
    '# Nia Agent Onboarding Prompt',
    '',
    'Run this workflow when you are setting up Nia for the user from an external coding agent session.',
    '',
    '## Goal',
    '',
    'Remove any legacy Python `nia-sync` install first, then install the new Nia CLI, direct the user to retrieve their API key manually, ask them to paste the key back to you, and finish CLI authentication and skill setup.',
    '',
    '## Steps',
    '',
    '1. Check for the legacy Python `nia-sync` CLI:',
    '',
    '- If `uv` is installed, run:',
    '',
    '```bash',
    'uv tool list',
    '```',
    '',
    '- If Python pip is available, run:',
    '',
    '```bash',
    'python3 -m pip show nia-sync',
    '```',
    '',
    '2. If `nia-sync` is installed, uninstall it before continuing:',
    '',
    '- For `uv`, run:',
    '',
    '```bash',
    'uv tool uninstall nia-sync',
    '```',
    '',
    '- For pip, run:',
    '',
    '```bash',
    'python3 -m pip uninstall -y nia-sync',
    '```',
    '',
    '- Then remove the legacy config file and delete the directory if it is empty:',
    '',
    '```bash',
    'rm -f ~/.nia-sync/config.json && rmdir ~/.nia-sync 2>/dev/null || true',
    '```',
    '',
    '3. Check whether Bun is installed:',
    '',
    '```bash',
    'bun --version',
    '```',
    '',
    '4. Install `@nozomioai/nia@latest` globally:',
    '',
    '- If `bun --version` succeeds, run:',
    '',
    '```bash',
    'bun add -g @nozomioai/nia@latest',
    '```',
    '',
    '- If `bun --version` fails, run:',
    '',
    '```bash',
    'npm install -g @nozomioai/nia@latest',
    '```',
    '',
    '5. Tell the user to open this URL and sign in:',
    '',
    '`https://app.trynia.ai/api-keys`',
    '',
    '6. Tell the user to create an API key on that page and copy the `nk_...` token.',
    '',
    '7. Ask the user to paste the API key back into the agent chat or session.',
    '',
    '8. After the user provides the key, configure the CLI:',
    '',
    '```bash',
    'nia auth login --api-key <nk_api_key>',
    '```',
    '',
    '9. Configure Nia skills:',
    '',
    '```bash',
    'nia skill --all',
    '```',
    '',
    '## Agent Message Template',
    '',
    'Send the user a message like this:',
    '',
    '> I need your Nia API key to finish setup. Please open https://app.trynia.ai/api-keys, sign in, create a key, and paste the `nk_...` value here. Once you send it, I will finish the setup for you.',
    '',
    '## Expected Result',
    '',
    'Any legacy `nia-sync` install is removed, `nia` now points to `@nozomioai/nia`, authentication is configured with the user-provided API key, and `nia skill --all` has completed.',
  ].join('\n');
}

export function printAgentGuide(): void {
  console.log(getAgentGuideMarkdown());
}
