const AGENT_GUIDE_MARKDOWN = [
  '# Nia Agent Onboarding (Headless)',
  '',
  'Use this flow when an agent cannot complete browser-based setup.',
  '',
  '## Base URL',
  '',
  '`https://apigcp.trynia.ai/v2`',
  '',
  '## New Account',
  '',
  '1. Create account + bootstrap token:',
  '',
  '```bash',
  'curl -sS -X POST "https://apigcp.trynia.ai/v2/auth/signup" \\',
  '  -H "Content-Type: application/json" \\',
  "  -d '{\"email\":\"agent@example.com\",\"password\":\"strong-password-123\",\"organization_name\":\"Agent Org\"}'",
  '```',
  '',
  '2. Exchange bootstrap token for API key:',
  '',
  '```bash',
  'curl -sS -X POST "https://apigcp.trynia.ai/v2/auth/bootstrap-key" \\',
  '  -H "Content-Type: application/json" \\',
  "  -d '{\"bootstrap_token\":\"<bootstrap-token>\"}'",
  '```',
  '',
  '## Existing Account',
  '',
  'Create API key directly with email/password:',
  '',
  '```bash',
  'curl -sS -X POST "https://apigcp.trynia.ai/v2/auth/login-key" \\',
  '  -H "Content-Type: application/json" \\',
  "  -d '{\"email\":\"agent@example.com\",\"password\":\"strong-password-123\"}'",
  '```',
  '',
  '## Install Nia Skill (Non-Interactive)',
  '',
  'Install for all detected agents:',
  '',
  '```bash',
  'npx nia-wizard skill add \\',
  '  --api-key "<nk_api_key>" \\',
  '  --source nozomio-labs/nia-skill \\',
  '  --all-agents \\',
  '  --non-interactive \\',
  '  --ci',
  '```',
  '',
  'Install for one target agent:',
  '',
  '```bash',
  'npx nia-wizard skill add \\',
  '  --api-key "<nk_api_key>" \\',
  '  --source nozomio-labs/nia-skill \\',
  '  --non-interactive \\',
  '  --ci',
  '```',
  '',
  'Target pinning example:',
  '',
  '```bash',
  'npx nia-wizard skill add --api-key "<nk_api_key>" --target codex --non-interactive --ci',
  '```',
  '',
  'Supported `--target` values:',
  '',
  '`amp`, `kimi-cli`, `replit`, `universal`, `antigravity`, `augment`, `claude-code`, `openclaw`, `cline`, `codebuddy`, `codex`, `command-code`, `continue`, `cortex`, `crush`, `cursor`, `droid`, `gemini-cli`, `github-copilot`, `goose`, `junie`, `iflow-cli`, `kilo`, `kiro-cli`, `kode`, `mcpjam`, `mistral-vibe`, `mux`, `opencode`, `openhands`, `pi`, `qoder`, `qwen-code`, `roo`, `trae`, `trae-cn`, `windsurf`, `zencoder`, `neovate`, `pochi`, `adal`',
  '',
  '## Command',
  '',
  'Print this guide any time:',
  '',
  '```bash',
  'npx nia-wizard agent-guide',
  '```',
].join('\n');

export function printAgentGuide(): void {
  console.log(AGENT_GUIDE_MARKDOWN);
}
