export function getAgentGuideMarkdown(): string {
  return [
    '# Nia Agent Onboarding Prompt',
    '',
    'Run this workflow when you are setting up Nia for the user from an external coding agent session.',
    '',
    '## Goal',
    '',
    'Install the Nia CLI, create an account via the passwordless API, verify the user\'s email, then finish CLI authentication and skill setup. No browser or manual key creation needed.',
    '',
    '## Steps',
    '',
    '### 1. Ask the user for their details',
    '',
    'Before doing anything, ask the user for:',
    '- **Email address**',
    '- **Organization name** (e.g. their company or team name)',
    '',
    '### 2. Install the Nia CLI',
    '',
    'Check whether Bun is installed:',
    '',
    '```bash',
    'bun --version',
    '```',
    '',
    'If `bun --version` succeeds:',
    '',
    '```bash',
    'bun add -g @nozomioai/nia@latest',
    '```',
    '',
    'If `bun --version` fails:',
    '',
    '```bash',
    'npm install -g @nozomioai/nia@latest',
    '```',
    '',
    '### 3. Create an account via the API',
    '',
    'Call the signup endpoint with the user\'s email and organization name. No password required.',
    '',
    '```bash',
    'curl -s -X POST https://apigcp.trynia.ai/v2/auth/signup \\',
    '  -H "Content-Type: application/json" \\',
    '  -d \'{"email": "<USER_EMAIL>", "organization_name": "<ORG_NAME>"}\'',
    '```',
    '',
    'The response contains:',
    '- `api_key`: a read-only `nk_...` key (upgraded to full access after verification)',
    '- `api_key_id`, `user_id`, `organization_id`',
    '- `verified`: false (until email is verified)',
    '',
    'A 6-digit verification code is sent to the user\'s email.',
    '',
    '### 4. Ask the user for the verification code',
    '',
    'Tell the user to check their email for a 6-digit code from Nia and paste it back.',
    '',
    '### 5. Verify the account',
    '',
    'Call the verify endpoint with the code and the API key from step 3:',
    '',
    '```bash',
    'curl -s -X POST https://apigcp.trynia.ai/v2/auth/verify \\',
    '  -H "Content-Type: application/json" \\',
    '  -H "Authorization: Bearer <nk_api_key>" \\',
    '  -d \'{"code": "<6_DIGIT_CODE>"}\'',
    '```',
    '',
    'On success, the API key is upgraded from read-only to full access.',
    '',
    '### 6. Configure the CLI',
    '',
    '```bash',
    'nia auth login --api-key <nk_api_key>',
    '```',
    '',
    '### 7. Install Nia skills',
    '',
    '```bash',
    'nia skill --all',
    '```',
    '',
    '## Agent Message Templates',
    '',
    '**Asking for details:**',
    '',
    '> To set up Nia, I need two things from you:',
    '> 1. Your **email address**',
    '> 2. An **organization name** (your company or team name)',
    '',
    '**Asking for verification code:**',
    '',
    '> I\'ve created your Nia account! Check your email for a 6-digit verification code from Nia and paste it here. This upgrades your API key to full access.',
    '',
    '## Expected Result',
    '',
    '`nia` is installed, the user\'s account is created and verified via API, the CLI is authenticated with a full-access API key, and `nia skill --all` has completed.',
  ].join('\n');
}

export function printAgentGuide(): void {
  console.log(getAgentGuideMarkdown());
}
